version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    # ports:
    #   - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend_api:
    image: supnex_code_challenge
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: develop
      APP_PORT: '${APP_PORT}'
      API_PREFIX: '${API_PREFIX}'
      SWAGGER_DOCUMENT_URL: ${SWAGGER_DOCUMENT_URL}
      DATABASE_TYPE: '${DATABASE_TYPE}'
      DATABASE_HOST: postgres
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_SYNCHRONIZE: '${DATABASE_SYNCHRONIZE}'
      DATABASE_MAX_CONNECTIONS: '${DATABASE_MAX_CONNECTIONS}'
    ports:
      - '${APP_PORT}:${APP_PORT}'
volumes:
  pgdata:
